name: 'Test Action'

on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read
  checks: write

jobs:
  test-action:
    name: 'Test Action'
    runs-on: ubuntu-latest

    steps:
      - name: 'Setup Repository (${{github.event.repository.name}})'
        uses: actions/checkout@v4
      
      - name: 'Test Action input'
        id: test
        uses: './'
        with:
          label-text: 'Label-123'
          status-text: 'Status-123'
          

      - name: 'Test Action output'
        run: |
          echo "Output: ${{ steps.test.outputs.custom-text-output }}"

