name: 'Test Action'

on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: write
  checks: write

jobs:
  test-action:
    name: 'Test Action'
    runs-on: ubuntu-24.04

    steps:
      - name: 'Setup Repository (${{ github.event.repository.name }})'
        uses: actions/checkout@v4
      
      - name: 'Run Action'
        id: test
        uses: './'
        with:
          label-text: 'Label-123'
          state-text: 'State-123'
      
      - name: 'Remove old badge'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin badge || true
          git checkout badge || git checkout --orphan badge

          git rm -rf . --ignore-unmatch

      - name: 'Write SVG'
        run: |
          echo -e '${{ steps.test.outputs.svg-text }}' > badge.svg

      - name: 'Commit SVG'
        run: |
          git add badge.svg
          git commit -m "Update badge" || echo "No changes"
          git push origin badge

      - name: 'Write summary'
        run: |
          RAW_URL="https://raw.githubusercontent.com/${{ github.repository }}/badge/badge.svg"
          echo '# Generated Badge' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "![badge.svg]($RAW_URL)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo -e '```svg\n${{ steps.test.outputs.svg-text }}\n```' >> $GITHUB_STEP_SUMMARY


