name: 'Test Action'

on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read
  checks: write

jobs:
  test-action:
    name: 'Test Action'
    runs-on: ubuntu-24.04

    steps:
      - name: 'Setup Repository (${{ github.event.repository.name }})'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}
      
      - name: 'Test Action input'
        id: test
        uses: './'
        with:
          label-text: 'Label-123'
          status-text: 'Status-123'

      - name: 'Test Action output'
        run: |
          echo '<h3>Generated Badge</h3>' >> $GITHUB_STEP_SUMMARY
          echo '<img src="data:image/svg+xml;utf8,${{ steps.test.outputs.svg-text }}" />' >> $GITHUB_STEP_SUMMARY


